### ISSUE TITLE
1000+ deviations in inbox may cause problems

### ISSUE THREAD

**Issue by ghost** [surdu/deviantAnywhere-chrome#1]
It was reported that more than 1000 deviations in the inbox will not display properly. This should be confirmed and fixed if observed to be true

**Comment by jamujamu** [comment]
I'm at 1133 Deviations right now and am experiencing no issues. Will post again if they arise.

2337 and still no issues.

**Comment by ghost** [comment]
And what Firefox do you use ?

**Comment by jamujamu** [comment]
Firefox 4.0 The one that was released like two days ago.

**Comment by ghost** [comment]
Do you have by any chance also 3.6, to check also on that one? Or you had it also on 3.6 with no problem ?

**Comment by jamujamu** [comment]
Posting from 3.6.11 as my deviations are being correctly updated. Works with PaleMoon 3.6.14 too.
