### ISSUE TITLE
Cannot read property 'result' of undefined

### ISSUE THREAD

**Issue by malenalbc** [surdu/deviantAnywhere-chrome#17]
TypeError: Cannot read property 'result' of undefined
at DiFi_countMessages (js/difi.js:298:128)
at XMLHttpRequest.DiFi_JSONrequest.xhr.onreadystatechange (js/difi.js:80:4)

![_bug](https://f.cloud.github.com/assets/4637279/622235/325d937a-cf36-11e2-8370-0cce57b0f788.jpg)

**Comment by kav2k** [comment]
Errr, wrong notifier! :)
It's a bug for my notifier and not deviantAnywhere.
Please contact me on dA (logeg)

**Comment by kav2k** [comment]
Postal2600, you can close this as fixed :smiling_imp:
For the record: dA retired News Articles, that causes queries to throw a tantrum
