### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by Turbo740** [surdu/deviantAnywhere-chrome#18]
I've been using DeviantAnywhere for a while now (about a year or so) and i've never ran into any problems before, but for some reason, it's not displaying anything whatsoever now, it has the picture of the deviantart fella, and the text deviantAnywhere, but nothing Else.

I've tried uninstalling and re-installing it (both the add on and firefox) and even tried downloading it on google chrome, but it's still not working.

**Comment by kav2k** [comment]
I guess it ran into the same problem as my Notifier did. I already patched mine.
DeviantART removed News Articles, and any queries to their servers that mention them result in massive errors.

**Comment by kav2k** [comment]
Blocked by #20
