### ISSUE TITLE
Adapt Chrome version for manifest version 2

### ISSUE THREAD

**Issue by kav2k** [surdu/deviantAnywhere-chrome#20]
Chrome manifest version 2 comes with a mandatory strict Content Security Policy.
Changes are required for the extension to work under it, and the Web Store version cannot be updated until it's done.

**Comment by kav2k** [comment]
Possibly will have to bump jQuery version.

**Comment by ghost** [comment]
Fixed. Can be found in the store version. Commit still pending tho ...
